format_version: 10
pipelines:
  graph:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-41d0a6a:
        git: https://github.com/littxx/graph
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
      - stage:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            test:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - start
                    command: npm
                    run_if: passed
